#!/usr/bin/env bash
# massoh verb: agents-md — emit a concise AGENTS.md team-index at the repo root.
# Reads $MASSOH_HOME/claude/agents/massoh-*.md frontmatter (name, description, tools)
# and writes a 7-row markdown table + workflow pointer.
#
# AM1: || true on ALL reads; degrade exit 0 if no role files (no file created).
# AM2: sentinel <!-- massoh-generated --> on line 1; overwrite if sentinel present;
#      refuse+exit 1 if AGENTS.md exists without sentinel (hand-authored).
# AM3: frontmatter parsed as data only (grep/sed — no source/eval/bash -c);
#      name≤64, description≤256+...; edits-code from tools: Edit or Write.
# AM4: _agents_md_sanitize_cell pipes→/ newlines→space; applied to name+description.
# AM5: output = sentinel + header + 7-row table + workflow pointer; < 50 lines.
# AM6: set -euo pipefail; if/else not A&&B||C.
# AM8: no secrets, no network, no LLM.
# Sourced by bin/massoh at startup. Requires: say, die, MASSOH_HOME (set in bin/massoh).
# shellcheck source=/dev/null

# AM6: set -euo pipefail inherited from bin/massoh bootstrap (already set globally).
# Declaring it again here is safe and explicit.
set -euo pipefail

# AGENTS_MD_SENTINEL: the exact sentinel string written to line 1 of every generated AGENTS.md.
# AM2: must match exactly on read-back checks.
AGENTS_MD_SENTINEL="<!-- massoh-generated -->"

# _agents_md_sanitize_cell: collapse newlines→space and replace pipes→/ (AM4).
# Safe for markdown table cells. No jq, no network.
_agents_md_sanitize_cell() {
  printf '%s' "${1:-}" \
    | tr '\n' ' ' \
    | sed 's/|/\//g' || true
}

# _agents_md_cap: truncate a string to at most N chars, appending ... if trimmed.
# Usage: _agents_md_cap <string> <max_chars>
_agents_md_cap() {
  local val="$1" max="$2"
  if [ "${#val}" -gt "$max" ]; then
    printf '%s' "${val:0:$max}..."
  else
    printf '%s' "$val"
  fi
}

cmd_agents_md() {
  local repo
  repo="$(git -C "$PWD" rev-parse --show-toplevel 2>/dev/null || echo "$PWD")"
  local target="$repo/AGENTS.md"

  # --- collect role files (AM1: glob; if no matches loop body never executes) ---
  local role_dir="$MASSOH_HOME/claude/agents"
  local found=0
  for _f in "$role_dir"/massoh-*.md; do
    if [ -f "$_f" ]; then
      found=$((found + 1))
    fi
  done

  if [ "$found" -eq 0 ]; then
    # AM1: degrade — no role files; exit 0; do NOT create AGENTS.md
    say "massoh agents-md: no role files found at $role_dir/ — is Massoh installed?"
    return 0
  fi

  # --- AM2: clobber policy ---
  if [ -f "$target" ]; then
    if grep -qF "$AGENTS_MD_SENTINEL" "$target" 2>/dev/null; then
      : # sentinel present — safe to overwrite (generated file)
    else
      # No sentinel — hand-authored; refuse
      printf 'massoh agents-md: AGENTS.md exists but was not generated by Massoh (no sentinel).\n' >&2
      printf '  Refusing to overwrite. Delete it or add '"'"'<!-- massoh-generated -->'"'"' to allow overwrite.\n' >&2
      return 1
    fi
  fi

  # --- build table rows ---
  # Each row: | name | description | edits code? |
  local rows=""
  for _f in "$role_dir"/massoh-*.md; do
    [ -f "$_f" ] || continue

    # AM3: parse frontmatter between first --- and second ---; head -n1 per field; no source/eval
    local raw_name raw_desc raw_tools
    raw_name="$(awk '/^---/{n++;next} n==1 && /^name:/{print;exit}' "$_f" 2>/dev/null \
      | sed 's/^name:[[:space:]]*//' | head -n1 || true)"
    raw_desc="$(awk '/^---/{n++;next} n==1 && /^description:/{print;exit}' "$_f" 2>/dev/null \
      | sed 's/^description:[[:space:]]*//' | head -n1 || true)"
    raw_tools="$(awk '/^---/{n++;next} n==1 && /^tools:/{print;exit}' "$_f" 2>/dev/null \
      | sed 's/^tools:[[:space:]]*//' | head -n1 || true)"

    # AM3: cap lengths
    local capped_name capped_desc
    capped_name="$(_agents_md_cap "$raw_name" 64)"
    capped_desc="$(_agents_md_cap "$raw_desc" 256)"

    # AM4: sanitize for table cells
    local cell_name cell_desc
    cell_name="$(_agents_md_sanitize_cell "$capped_name")"
    cell_desc="$(_agents_md_sanitize_cell "$capped_desc")"

    # AM3: edits code? — check if tools contains Edit or Write
    local edits_code="no"
    if printf '%s' "$raw_tools" | grep -qE '\bEdit\b|\bWrite\b' 2>/dev/null; then
      edits_code="yes"
    fi

    rows="${rows}| ${cell_name} | ${cell_desc} | ${edits_code} |
"
  done

  # --- AM5: assemble output (sentinel + header + table + workflow pointer; < 50 lines) ---
  local content
  content="${AGENTS_MD_SENTINEL}
# Massoh Agent Team

| Role | Description | Edits code? |
|---|---|---|
${rows}
> Workflow: see [agent-os/policies/03_AGENT_WORKFLOW.md](agent-os/policies/03_AGENT_WORKFLOW.md)
"

  # AM2: write (overwrite if sentinel was already present, or create fresh)
  printf '%s' "$content" > "$target"
  say "massoh agents-md: wrote $target (${found} roles)"
}
